# Exercise 2

# 1
print('*')

#2
print()
print('***')
print('*' * 5)

#3
print()
print('*')
print('*' * 2)
print('*' * 3)
print('*' * 4)
print('*' * 5)
print('*' * 6)
print('*' * 7)
print('*' * 8)
print('*' * 9)
print('*' * 10)

#4
print()
print('*' * 10)
print('*' * 9)
print('*' * 8)
print('*' * 7)
print('*' * 6)
print('*' * 5)
print('*' * 4)
print('*' * 3)
print('*' * 2)
print('*')

#5
print()
print('*' + ' ' * 18 + '*')
print('*' * 2 + ' ' * 16 + '*' * 2)
print('*' * 3 + ' ' * 14 + '*' * 3)
print('*' * 4 + ' ' * 12 + '*' * 4)
print('*' * 5 + ' ' * 10 + '*' * 5)
print('*' * 6 + ' ' * 8 + '*' * 6)
print('*' * 7 + ' ' * 6 + '*' * 7)
print('*' * 8 + ' ' * 4 + '*' * 8)
print('*' * 9 + ' ' * 2 + '*' * 9)
print('*' * 10 + ' ' * 0 + '*' * 10)

#6
print()
print(' ' * 9 + '*')
print(' ' * 8 + '*' * 4)
print(' ' * 7 + '*' * 6)
print(' ' * 6 + '*' * 8)
print(' ' * 5 + '*' * 10)
print(' ' * 4 + '*' * 12)
print(' ' * 3 + '*' * 14)
print(' ' * 2 + '*' * 16)
print(' ' * 1 + '*' * 18)
print(' ' * 0 + '*' * 20)
print(' ' * 0 + '*' * 20)
print(' ' * 1 + '*' * 18)
print(' ' * 2 + '*' * 16)
print(' ' * 3 + '*' * 14)
print(' ' * 4 + '*' * 12)
print(' ' * 5 + '*' * 10)
print(' ' * 6 + '*' * 8)
print(' ' * 7 + '*' * 6)
print(' ' * 8 + '*' * 4)
print(' ' * 9 + '*')

#7
char = input('Please enter a character to use when drawing the triangle ')
print()
print(char)
print(char * 2)
print(char * 3)
print(char * 4)
print(char * 5)
print(char * 6)
print(char * 7)
print(char * 8)
print(char * 9)
print(char * 10)
